version: '2'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - ".mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: devstats
      MYSQL_USER: devstats
      MYSQL_PASSWORD: devstats

  grafana:
    image: grafana/grafana:6.4.2
    volumes:
      - ".grafana-storage:/var/lib/grafana"
    ports:
      - 3000:3000
    user: "472"
